apiVersion: v1
kind: Service
metadata:
  name: fintech-service
  namespace: fintech
spec:
  selector:
    app: fintech-app
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30081